### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by CatzMR** [BadJuju22/BadJujuRolePlayHUD#1]
![YARLEB_RM2RK_8ZPKBZ9KL3](https://user-images.githubusercontent.com/62692767/208901216-e2d73e90-87c8-4524-833b-aa71c911ef05.png)
I can't solve this problem with this plugin
And I don't have a suitable legend icon, can you make public what you use?

**Comment by CatzMR** [comment]
@BadJuju22

**Comment by BadJuju22** [comment]
I'm making new version
I think errors caused non existing of GPS points
